language: java
notifications:
  slack:
    secure: RCdmR01sviXs2gjESzzu1+Sr3SAoQ4wN/t0fJEmB3QA6kLkXR+rgraQ6OytaxpM246f+ozWahT9/3CrBv8OMIn08/U1hX74iHOhAP7TPxEFhb0sMlrHIUR3HJfUj+bfl/QesC/I2KtAWhCtSJVj8FxS9TEIyN7TvNFLc6hlDGPo=
deploy:
  provider: releases
  api_key:
    secure: mXgUhJe9u5xPCgYVHflB//q0vbon65hx4DWrMBLqnYl01vL/TvOYCb2YORoZIN1dxEVF9cYP1Qcbw3qx9OEF4T58BTD1zB7W8wyA3pJqgSAtA1Gc05bXPu0gD0y0Vxd94Cyo7jgE9GI5SmGNRqxG1750HimQCqffhxaD3D6oZ6A=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-nodejs-plugin
