language: java
notifications:
  hipchat:
    rooms:
      secure: Ql0WM1tVMCBmvVo/xXfkYf6HvMn7T9iWTWpUiWITDRwE2JjZ027Em1s31M6T1q9tmTRy1wjWmnlOqVWklIzRaJtxL/u/GImGPV9LIiYA4vkhY/si23xjN5xqqVKy2afpjx6i1E+GoFftTRafwleUdVb5Cz9nvMgvAMiVl1P+Xlc=
deploy:
  provider: releases
  api_key:
    secure: SSQzk9Igq6SeAmNXipVNzxp5qt7oNbUly3fChH+f4Yd0qoNxka1KpGGALrM3kb+wpS5voXjtdRjpPh/ad+yabLOM6rfTIUOoZjFGchxW49f5sgPjIZpiKcO9BO9ZbnBP/0ToUGDvarJPGpINnmiDEFXLS/YOtfHJBr9NwUAMoBc=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-nodejs-plugin
