language: java
notifications:
  hipchat:
    rooms:
      secure: Ql0WM1tVMCBmvVo/xXfkYf6HvMn7T9iWTWpUiWITDRwE2JjZ027Em1s31M6T1q9tmTRy1wjWmnlOqVWklIzRaJtxL/u/GImGPV9LIiYA4vkhY/si23xjN5xqqVKy2afpjx6i1E+GoFftTRafwleUdVb5Cz9nvMgvAMiVl1P+Xlc=
deploy:
  provider: releases
  api_key:
    secure: mXgUhJe9u5xPCgYVHflB//q0vbon65hx4DWrMBLqnYl01vL/TvOYCb2YORoZIN1dxEVF9cYP1Qcbw3qx9OEF4T58BTD1zB7W8wyA3pJqgSAtA1Gc05bXPu0gD0y0Vxd94Cyo7jgE9GI5SmGNRqxG1750HimQCqffhxaD3D6oZ6A=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-nodejs-plugin
